mit anlegen des users sophomorix

diff --git a/debian/sophomorix-base.preinst b/debian/sophomorix-base.preinst
--- a/debian/sophomorix-base.preinst
+++ b/debian/sophomorix-base.preinst
@@ -1,22 +1,57 @@
 #! /bin/sh
+# preinst script for sophomorix-base
+#
+# see: dh_installdeb(1)
+
 set -e
 
-# Load the debconf library - this must come FIRST; do not insert any other
-# commands before this
-. /usr/share/debconf/confmodule
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+#
+# quoting from the policy:
+#     Any necessary prompting should almost always be confined to the
+#     post-installation script, and should be protected with a conditional
+#     so that unnecessary prompting doesn't happen if a package's
+#     installation fails and the `postinst' is called with `abort-upgrade',
+#     `abort-remove' or `abort-deconfigure'.
 
-if [ "$1" = install -o "$1" = upgrade ]
-then
+case "$1" in
+    configure)
+    # calling the setup-script of sophomorix
 
     # Make sure the administrative user sophomorix exists
     getent group sophomorix >/dev/null 2>&1 || addgroup --system sophomorix
     getent passwd sophomorix >/dev/null 2>&1 ||
-	adduser --system --shell /bin/bash --home /home/sophomorix --ingroup sophomorix --gecos "Sophomorix administrator" sophomorix
+	adduser --system --shell /bin/bash --home /var/lib/sophomorix --ingroup sophomorix --gecos "Sophomorix administrator" sophomorix
 
 
-fi # for 'if $1 = install|upgrade' at the top of file
 
+    sophomorix-setup
+    sophomorix-samba
+    ;;
 
+    abort-upgrade|abort-remove|abort-deconfigure)
+
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
 
